name: .NET Core

on: [push]

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: OpcIotHub
        path: /home/runner/work/opc-iot-hub/opc-iot-hub/OpcIotHub/bin/Release/net6.0/publish/